<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores[
<!ELEMENT marcadores (marcador*)>
<!--cambio favoritos por marcadores, ya que es  la etiqueta raíz-->
<!ELEMENT marcador (nombre, uri)>
<!--cambio favoritos por marcador, ya que es  la etiqueta hijo correspondiente-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT uri (#PCDATA)>
]>
<marcadores>
<marcador>
<nombre>W3C</nombre>
<uri>http://www.w3.org/</uri>
</marcador>
<marcador>
<nombre>Web Hypertext Application Technology Working Group
(WHATWG) </nombre>
<uri>http://www.whatwg.org/</uri>
</marcador>
</marcadores>